/**
 * WASM Module Loader
 * 
 * Handles loading and initialization of the Rust WASM physics module.
 */

// These types will be generated by wasm-pack
export interface WasmModule {
    WasmSimulation: WasmSimulationClass;
    WasmPcg: WasmPcgClass;
    circular_velocity: (centralMass: number, orbitalRadius: number) => number;
    escape_velocity: (centralMass: number, radius: number) => number;
    orbital_period: (centralMass: number, semiMajorAxis: number) => number;
    soi_radius: (semiMajorAxis: number, bodyMass: number, primaryMass: number) => number;
    hill_radius: (semiMajorAxis: number, bodyMass: number, primaryMass: number) => number;
    gravitational_constant: () => number;
    log: (message: string) => void;
    log_error: (message: string) => void;
}

export interface WasmSimulationClass {
    new(): WasmSimulationInstance;
    with_config(configJson: string): WasmSimulationInstance;
}

export interface WasmSimulationInstance {
    set_seed(seed: bigint, stream: bigint): void;
    tick(): bigint;
    sim_time(): number;
    sequence(): bigint;
    config_json(): string;
    set_config(configJson: string): void;
    add_body_json(bodyJson: string): void;
    add_body(
        id: string,
        name: string,
        mass: number,
        radius: number,
        px: number,
        py: number,
        pz: number,
        vx: number,
        vy: number,
        vz: number
    ): void;
    add_star(id: string, name: string, mass: number, radius: number, px: number, py: number, pz: number): void;
    add_planet(
        id: string,
        name: string,
        mass: number,
        radius: number,
        px: number,
        py: number,
        pz: number,
        vx: number,
        vy: number,
        vz: number
    ): void;
    remove_body(id: string): void;
    body_count(): number;
    active_body_count(): number;
    body_ids(): string;
    get_body(id: string): string | undefined;
    bodies_json(): string;
    initialize(): void;
    step(): string;
    step_n(n: bigint): void;
    reset(): void;
    checkpoint_json(): string;
    snapshot_json(): string;
    restore_checkpoint(json: string): void;
    get_positions(): Float64Array;
    get_velocities(): Float64Array;
    get_radii(): Float64Array;
    get_masses(): Float64Array;
    origin_offset(): Float64Array;
    energy_metrics(): string | undefined;
    momentum_metrics(): string | undefined;
    apply_body_states(statesJson: string): void;
    collision_events(): string;
    collision_count(): bigint;
    free(): void;
}

export interface WasmPcgClass {
    new(seed: bigint, stream: bigint): WasmPcgInstance;
    from_state(state: bigint, inc: bigint): WasmPcgInstance;
}

export interface WasmPcgInstance {
    next_u32(): number;
    next_f64(): number;
    next_f64_range(min: number, max: number): number;
    get_state(): BigUint64Array;
    free(): void;
}

let wasmModule: WasmModule | null = null;
let loadingPromise: Promise<WasmModule> | null = null;

/**
 * Load the WASM module
 * @param wasmPath Path to the WASM module (default: look for pkg/physics.js)
 */
export async function loadWasmModule(wasmPath?: string): Promise<WasmModule> {
    if (wasmModule) {
        return wasmModule;
    }

    if (loadingPromise) {
        return loadingPromise;
    }

    loadingPromise = (async () => {
        try {
            // Dynamic import of the WASM module
            const modulePath = wasmPath || '../pkg/physics.js';
            const module = await import(/* @vite-ignore */ modulePath);
            
            // Initialize the WASM module
            if (module.default) {
                await module.default();
            }

            wasmModule = module as WasmModule;
            return wasmModule;
        } catch (error) {
            loadingPromise = null;
            throw new Error(`Failed to load WASM module: ${error}`);
        }
    })();

    return loadingPromise;
}

/**
 * Get the loaded WASM module (throws if not loaded)
 */
export function getWasmModule(): WasmModule {
    if (!wasmModule) {
        throw new Error('WASM module not loaded. Call loadWasmModule() first.');
    }
    return wasmModule;
}

/**
 * Check if WASM module is loaded
 */
export function isWasmLoaded(): boolean {
    return wasmModule !== null;
}

/**
 * Reset the WASM module (for testing)
 */
export function resetWasmModule(): void {
    wasmModule = null;
    loadingPromise = null;
}
