use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=src/constants.rs");

    let constants_path = Path::new("src/constants.rs");
    if !constants_path.exists() {
        return;
    }

    let rust_code = fs::read_to_string(constants_path).expect("Failed to read constants.rs");
    
    let mut ts_code = String::new();
    ts_code.push_str("// AUTO-GENERATED from physics-core/src/constants.rs\n");
    ts_code.push_str("// DO NOT EDIT DIRECTLY. This file is generated by build.rs.\n\n");

    for line in rust_code.lines() {
        let line = line.trim();
        if line.starts_with("pub const ") {
            // e.g. pub const G: f64 = 6.67430e-11;
            let parts: Vec<&str> = line.splitn(2, '=').collect();
            if parts.len() == 2 {
                let decl = parts[0].trim();
                let val = parts[1].trim().trim_end_matches(';');
                
                // Extract name
                let name_part = decl.strip_prefix("pub const ").unwrap();
                let name = name_part.split(':').next().unwrap().trim();
                
                // Rust uses underscores in numbers like 1_000.0, remove them for TS
                // But do NOT remove them from variable names like SECONDS_PER_DAY
                let mut clean_val = String::new();
                let bytes = val.as_bytes();
                for (i, &b) in bytes.iter().enumerate() {
                    let c = b as char;
                    if c == '_' {
                        let prev_is_digit = i > 0 && bytes[i - 1].is_ascii_digit();
                        let next_is_digit = i + 1 < bytes.len() && bytes[i + 1].is_ascii_digit();
                        if prev_is_digit && next_is_digit {
                            continue; // skip underscore inside a number
                        }
                    }
                    clean_val.push(c);
                }
                
                ts_code.push_str(&format!("export const {} = {};\n", name, clean_val));
            }
        }
    }

    // Write to shared directory
    let out_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("../shared/physics_constants.ts");
    fs::write(dest_path, ts_code).expect("Failed to write physics_constants.ts");
}
