export const CONFIG = {
  timeScale: 1,
  physicsTimeStep: 1 / 90,
  gravityConstant: 6.6743e-3,
  fidelityLevels: {
    low: {
      rendererPixelRatio: 0.75,
      maxParticles: 256,
      shadowMapSize: 512,
      lodEnabled: false,
    },
    medium: {
      rendererPixelRatio: 1,
      maxParticles: 512,
      shadowMapSize: 1024,
      lodEnabled: false,
    },
    ultra: {
      rendererPixelRatio: 1.25,
      maxParticles: 1024,
      shadowMapSize: 2048,
      lodEnabled: true,
    },
  },
  defaultFidelity: "medium",
  optimization: {
    frustumCulling: false,
  },
  celestialBodies: [
    {
      id: "sun",
      name: "Helios",
      type: "star",
      mass: 1.989e6,
      radius: 50,
      emissiveIntensity: 3,
      color: 0xffd27f,
      rotationSpeed: 0.0005,
      luminosity: 1.15,
      initialPosition: { x: 0, y: 0, z: 0 },
      initialVelocity: { x: 0, y: 0, z: 0 },
    },
    {
      id: "terra",
      name: "Terra",
      type: "planet",
      mass: 5.97e4,
      radius: 12.7,
      color: 0x4e8ef7,
      rotationSpeed: 0.0025,
      orbitalRadius: 300,
      orbitalSpeed: 6.64,
      initialPhase: 0,
    },
    {
      id: "astra",
      name: "Astra",
      type: "planet",
      mass: 1.898e5,
      radius: 28,
      color: 0xf97316,
      rotationSpeed: 0.0012,
      orbitalRadius: 520,
      orbitalSpeed: 5.05,
      initialPhase: Math.PI / 3,
    },
    {
      id: "selene",
      name: "Selene",
      type: "moon",
      parent: "terra",
      mass: 7.35e2,
      radius: 3.5,
      color: 0xe2e8f0,
      rotationSpeed: 0.0055,
      orbitalRadius: 30,
      orbitalSpeed: 3.63,
      initialPhase: Math.PI / 4,
    },
  ],
  microObjects: [
    {
      id: "microCrate",
      mass: 5,
      size: 1,
      position: { x: 312, y: 10, z: 6 },
      color: 0x94a3b8,
    },
    {
      id: "microProbe",
      mass: 2,
      size: 0.8,
      position: { x: 306, y: 11, z: -8 },
      color: 0x22d3ee,
    },
  ],
  specialEntities: [],
  player: {
    spawnPosition: { x: 312, y: 14, z: 12 },
    walkSpeed: 8,
    runMultiplier: 1.5,
    jumpImpulse: 6,
    flightSpeed: 18,
    gravitySnapThreshold: 110,
  },
};
